/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';


export namespace Components {

  interface MDashboard {}
  interface MDashboardAttributes extends StencilHTMLAttributes {}

  interface MRoot {}
  interface MRootAttributes extends StencilHTMLAttributes {}

  interface MUploadModal {
    'open': () => void;
  }
  interface MUploadModalAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'MDashboard': Components.MDashboard;
    'MRoot': Components.MRoot;
    'MUploadModal': Components.MUploadModal;
  }

  interface StencilIntrinsicElements {
    'm-dashboard': Components.MDashboardAttributes;
    'm-root': Components.MRootAttributes;
    'm-upload-modal': Components.MUploadModalAttributes;
  }


  interface HTMLMDashboardElement extends Components.MDashboard, HTMLStencilElement {}
  var HTMLMDashboardElement: {
    prototype: HTMLMDashboardElement;
    new (): HTMLMDashboardElement;
  };

  interface HTMLMRootElement extends Components.MRoot, HTMLStencilElement {}
  var HTMLMRootElement: {
    prototype: HTMLMRootElement;
    new (): HTMLMRootElement;
  };

  interface HTMLMUploadModalElement extends Components.MUploadModal, HTMLStencilElement {}
  var HTMLMUploadModalElement: {
    prototype: HTMLMUploadModalElement;
    new (): HTMLMUploadModalElement;
  };

  interface HTMLElementTagNameMap {
    'm-dashboard': HTMLMDashboardElement
    'm-root': HTMLMRootElement
    'm-upload-modal': HTMLMUploadModalElement
  }

  interface ElementTagNameMap {
    'm-dashboard': HTMLMDashboardElement;
    'm-root': HTMLMRootElement;
    'm-upload-modal': HTMLMUploadModalElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
